### ISSUE TITLE
Does not set DPI if it already exists

### ISSUE THREAD

**Issue by joelanman** [daiiz/png-pHYs-chunk-writer#23]
Firstly thanks for this! I've been working on trying to set PNG dpi for a while and this is the first library I found that works!

If I use this to set DPI on a file that doesn't have one, it works.

If I try and set DPI on a file that already has one, it does not work - the existing DPI is still set when I write the file.

**Comment by daiiz** [comment]
Thank you for the nice feedback!

At the moment, this is by design:
https://github.com/daiiz/png-dpi-reader-writer/blob/master/test/writer.js#L34

This was designed based on my use case at the time. However, after rethinking, it looks a little strange. I will consider to implement options for overriding DPI:
```js
writePngDpi(arrayBuffer, 72, { override: true })
```

**Comment by joelanman** [comment]
To be fair, I don't actually have a use case, it's just when I tried it on a bunch of files, some of the them didn't work. Then I realised it was because they already had DPI. So it was confusing, but in the actual task I'm doing I don't need to overwrite an existing DPI.
